### DISCUSSION TITLE
Portainer installation

### DISCUSSION THREAD

**Discussion by rgnd971** [Donkie/Spoolman#266] [Q&A] [answered]
Hello and sorry for my English, I'm French and I use deepl.
Is it possible to install Spoolman via Portainer on a NAS?
Thanks

**Comment by drlauridsen** [comment, marked as answer]
You can create the container manually in Portainer, or you can try the following code as a stack in Portainer

```
version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      # Mount the host machine's ./data directory into the container's /home/app/.local/share/spoolman directory
      - type: bind
        source: /dockervolumes/spoolman # This is where the data will be stored locally. Could also be set to for example `source: /home/pi/printer_data/spoolman`.
        target: /home/app/.local/share/spoolman # Do NOT change this line
    ports:
      # Map the host machine's port 7912 to the container's port 8000
      - "7912:8000"
    environment:
      - TZ=Europe/Copenhagen # Optional, defaults to UTC
```

Just change source to a folder on your NAS that is accessible to your containers

**Reply by rgnd971** [reply]
bonjour, I deleted the container then relaunched an update stack and it worked! I don't get it!

**Comment by rgnd971** [comment]
Thank you for your answer,
My container mounts fine, I access spoolman via port 7912, but in the container log I have a problem with the volume "/home/app/.local/share/spoolman", it is not mounted.
I don't have a /app directory on my NAS. I think this is where I should put a directory for my 3d printer?

**Reply by TexZeTech** [reply]
Could you post your stack in code blocks for others to look at please?


My stack is setup like this.

```
version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - spoolman:/home/app/.local/share/spoolman
      # Mount the host machine's ./data directory into the container's /home/app/.local/share/spoolman directory
      #- type: bind
      #  source: spoolman
        #source: ./data # This is where the data will be stored locally. Could also be set to for example `source: /home/pi/printer_data/spoolman`.
      #  target: /home/app/.local/share/spoolman # Do NOT change this line
        
    ports:
      # Map the host machine's port 7912 to the container's port 8000
      - "<PORT YOU WANT HERE>:8000"
    environment:
      - TZ=<Your timezone here> # Optional, defaults to UTC

volumes:
  spoolman:
    external: true
```

The external value might help ya, good luck.
```
volumes:
  spoolman:
    external: true
```
