### DISCUSSION TITLE
New to this stuff.

### DISCUSSION THREAD

**Discussion by Southcountycreations** [Donkie/Spoolman#603] [Q&A]
I am new to all of this. And admit I am lost. I have had this openspool machine now for about a month.  And can not figure out how to set anything up. If I may ask. Can someone please explain the setup ? The rest i will have to slowly learn. But just need in the startup

**Comment by Cfomodz** [comment]
1. **Install Docker**, then create `docker-compose.yml`:
   ```yaml
   version: '3.8'
   services:
     spoolman:
       image: ghcr.io/donkie/spoolman:latest
       restart: unless-stopped
       volumes:
         - ./data:/home/app/.local/share/spoolman
       ports:
         - "7912:8000"
       environment:
         - TZ=America/Denver
   ```

2. **Start Spoolman**:
   ```bash
   docker compose up -d
   ```

3. **Access**: Open `http://your-ip:7912` in your browser

## Setup Order (This is the key!)

### Step 1: Add Vendors
- Go to "Vendors" → "Add Vendor"
- Enter manufacturer name (e.g., "Hatchbox", "eSun")

### Step 2: Add Filament Types
- Go to "Filaments" → "Add Filament"
- Select vendor from dropdown
- Enter: Name, Material (PLA/PETG/etc), Color, Diameter (1.75mm)

### Step 3: Add Individual Spools
- Go to "Spools" → "Add Spool"
- Select filament type from dropdown
- Enter weight and location

**Important**: You must create Vendors → Filaments → Spools in that order. Each level depends on the previous one.

## Integration with Printer

### For Klipper/Moonraker:
Add to `moonraker.conf`:
```ini
[spoolman]
server: http://your-ip:7912
```

### For OctoPrint:
Install the "Spoolman" plugin from Plugin Manager and configure the server URL.

## Usage
1. Select active spool in your printer interface before printing
2. Spoolman automatically tracks filament usage during prints
3. View remaining filament in the web interface

**That's it!**
