### DISCUSSION TITLE
docker host port different than container port :thinking:

### DISCUSSION THREAD

**Discussion by kinghat** [Donkie/Spoolman#663] [Q&A]
why do the docker install instructions start the user off with a different host port than what the app uses inside the container? https://github.com/Donkie/Spoolman/wiki/Installation#first-install

**Comment by Cfomodz** [comment]
Simply change your `docker-compose.yml`:

```yaml
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    ports:
      - "8000:8000"  # Changed from 7912:8000
    volumes:
      - ./data:/home/app/.local/share/spoolman
    restart: unless-stopped
```

Then restart:
```bash
docker compose down && docker compose up -d
```
