### DISCUSSION TITLE
Migrate from stand alone to Docker container

### DISCUSSION THREAD

**Discussion by mfraser** [Donkie/Spoolman#718] [Q&A] [answered]
I've been running Spoolman for at least a year now as a stand alone service and was thinking about migrating over to a Docker container as it seems to be easier to update.

Is this something that is simple to do?

**Comment by Cfomodz** [comment, marked as answer]
### 1. Install Docker
```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker $USER
```
Log out and back in.

### 2. Stop Standalone Spoolman
```bash
sudo systemctl stop Spoolman
```

### 3. Backup Your Data
```bash
mkdir -p ~/spoolman_backup
cp ~/.local/share/spoolman/spoolman.db ~/spoolman_backup/
```
(Adjust path if you used custom `SPOOLMAN_DIR_DATA`)

### 4. Create Docker Setup
```bash
mkdir -p ~/spoolman/data
cp ~/.local/share/spoolman/spoolman.db ~/spoolman/data/
sudo chown -R 1000:1000 ~/spoolman/data
```

### 5. Create docker-compose.yml
```bash
cd ~/spoolman
nano docker-compose.yml
```

Paste:
```yaml
version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - ./data:/home/app/.local/share/spoolman
    ports:
      - "7912:8000"
    environment:
      - TZ=America/Denver
```

### 6. Start Docker Container
```bash
docker compose up -d
```

### 7. Verify
Open `http://localhost:7912` and confirm your data appears.

## Update Command
```bash
cd ~/spoolman
docker compose pull && docker compose up -d
```
