### ISSUE TITLE
Cant select any spool in moonraker

### ISSUE THREAD

**Issue by Mr-Boshi** [Donkie/Spoolman#171]
Hi!
I've deployed the Spoolman with postgress for db in docker as a stack. It runs ok, the webui works pretty good but I cannot select any spool in moonraker. The logs show that no matter what spool I select or no matter the ID I pass to the set_active_spool macros it sends the request with the ID=0:
`"PUT /spool/0/use HTTP/1.1" 404 Not Found`

This is the contents of the compose file:

```
spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    container_name: spoolman
    ports:
      - "7912:8000"
    environment:
      - TZ=Europe/Moscow
      - SPOOLMAN_DB_TYPE=postgres
      - SPOOLMAN_DB_HOST=spoolman-db
      - SPOOLMAN_DB_NAME=spoolman
      - SPOOLMAN_DB_USERNAME=app
      - SPOOLMAN_DB_PASSWORD=app
      - SPOOLMAN_DB_PORT=5432

  spoolman-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    container_name: spoolman-db
    volumes:
      - ./spoolman/db/data:/var/lib/postgresql/data
      - ./spoolman/db/config/sql:/config/sql
    environment:
      POSTGRES_DB: spoolman
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
```

I've tried the latest image and the 0.12.2 image, same result.

[Here is a video](https://www.reddit.com/r/klippers/comments/17fkr0q/cant_select_spool_in_spoolman/) of how it looks in mainsale I've posten on Reddit.
