### ISSUE TITLE
Volumes instead of bind for the compose example?

### ISSUE THREAD

**Issue by exen904** [Donkie/Spoolman#208]
I migrated my Docker Host recently and noticed, that I did not have specified a permanent storage point for the container data. As I am fairly new to docker, I overlooked that when creating the Container via Compose. I tried re-creating it now with the `compose.yml` in the Readme. 

I had some issues with the permissions using the example data. I looked it up in the Docker documentation and they suggest to use [Volumes](https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose) instead of binds if possible. So I went that way and had a really easy re-setup. 

I would suggest to change the example also to the use of Volumes, as it makes the installation for new users also easier. 

My `compose.yml`

```
version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - spoolman:/home/node/spoolman
    ports:
      # Map the host machine's port 7912 to the container's port 8000
      - "7912:8000"
    environment:
      - TZ=Europe/Berlin # Optional, defaults to UTC
volumes:
  spoolman:
```
