### ISSUE TITLE
Permissions error after upgrading to 0.18.1

### ISSUE THREAD

**Issue by Tam-Lin** [Donkie/Spoolman#412]
**Describe the bug**

I'm using the docker image from ghcr.io/donkie/spoolman:latest.  I rebooted the docker host, and upon restart, I'm getting (this may be similar to #382, but I believe I have version 0.18.1 that is supposed to fix the permissions error, which was for different files anyway):

```

INFO:     Started server process [1]
INFO:     Waiting for application startup.
spoolman.env               WARNING  Data directory is not writable, trying to fix it...
chown: /home/app/.local/share/spoolman/cache/materials.json: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/filaments.json: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/hishel/.gitignore: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/hishel/7092233f1b6dfd51f4c1d26c6e64c49a: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/hishel/4203b6c338b99a0428310bad4f723b5d: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/hishel: Operation not permitted
chown: /home/app/.local/share/spoolman/cache/hishel: Operation not permitted
chown: /home/app/.local/share/spoolman/cache: Operation not permitted
chown: /home/app/.local/share/spoolman/cache: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.db: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db.5: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db.1: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db.4: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db.2: Operation not permitted
chown: /home/app/.local/share/spoolman/backups/spoolman.db.3: Operation not permitted
chown: /home/app/.local/share/spoolman/backups: Operation not permitted
chown: /home/app/.local/share/spoolman/backups: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log.2024-06-04: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log.2024-06-03: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log.2024-06-02: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log.2024-06-06: Operation not permitted
chown: /home/app/.local/share/spoolman/spoolman.log.2024-06-05: Operation not permitted
chown: /home/app/.local/share/spoolman: Operation not permitted
chown: /home/app/.local/share/spoolman: Operation not permitted
spoolman.env               ERROR    Data directory is not writable. Please run "sudo chown -R 1000:1001 /path/to/spoolman/datadir" on the host OS.
ERROR:    Traceback (most recent call last):
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/home/app/spoolman/spoolman/main.py", line 117, in startup
    env.check_write_permissions()
  File "/home/app/spoolman/spoolman/env.py", line 374, in check_write_permissions
    sys.exit(1)
SystemExit: 1
ERROR:    Application startup failed. Exiting.

```

In the host, the files are owned by userid docker, group docker, which is UID 1001, GID 1002.  In the docker environment, I've specified 

```
PUID=1001
PGID=1002
```

Running chown -R 1000:1001 * in the host data directory does fix things, but shouldn't be necessary I don't believe.

**To Reproduce**

I'm not sure; I'm not sure why I'm seeing this now as opposed to with version 0.18.0.

**Expected behavior**

Specifying PUID and PGID in the environmental variables should allow it to access the files.

**Spoolman Host (please complete the following information):**
 - Installation type: Docker
 - Installed version: 0.18.1
 - OS and Distro: Ubuntu
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android, ...] N/A
 - Browser [e.g. Chrome, Firefox, Safari, ...] N/A

**Additional context**

**Comment by Donkie** [comment]
Seems to me like your PUID and PGID settings are not being applied correctly to your container, I just tried myself to change them in the environment section of the docker compose, and the `sudo chown` command it suggests in the error gets the same PUID and PGID values that I set, e.g. for you it should look like:
![image](https://github.com/user-attachments/assets/9fa86999-4e4c-4600-b0d8-a3da932f9c30)

But by checking your log it's infact telling you to set it to "1000:1001"

**Comment by NonaSuomy** [comment]
Any idea why I would still be getting this error while on latest 
Failed to setup disk-based cache due to permission error. Ensure the path /home/app/.local/share/spoolman/cache/hishel is writable. Using in-memory cache instead as fallback.
/opt/docker-storage/spoolman$ sudo chown 1000:1001 -R data
/opt/docker-storage/spoolman$ ls -lah
total 12K
drwxr-xr-x  3 nonasuomy 1001 4.0K Oct 18  2024 .
drwxr-xr-x 28 root      root 4.0K Apr 29 13:02 ..
drwxr-xr-x  2 nonasuomy 1001 4.0K Oct 18  2024 data 

```yaml
# Spoolman Container for Docker https://github.com/Donkie/Spoolman
services:
  spoolman:
    container_name: "spoolman"
    hostname: "spoolman"
    image: ghcr.io/donkie/spoolman:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
       - /opt/docker-storage/spoolman/data:/home/app/.local/share/spoolman
    networks:
      dhcp:
        mac_address: "9e:57:59:8e:5e:41"
    #restart: "no"
    #restart: "unless-stopped"
    restart: "always"
    ports:
      - "7912:8000"
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Toronto # Optional, defaults to UTC
      - PUID=1001
      - PGID=1002
networks:
  dhcp:
    name: "dbrv700"
    external: true
```
