### ISSUE TITLE
Designate a QR code value for the act of clearing the set spool 

### ISSUE THREAD

**Issue by Laikulo** [Donkie/Spoolman#418]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
I would like an officially designated value for the `web+spoolman:` scheme for clearing the active spool in software that integrates with spoolman (e.g. Moonraker)

**Describe alternatives you've considered**
* Using a different scheme (e.g. `moonraker:clear-spool`)
* Using the special value "0" `web+spoolman:sp-0`

**Additional context**
I have a barcode scanner hooked up to ESPHome, that generates API requests to moonraker whenever a spoolman QR is scanned. Since I also need a way to suspend tracking, I am currently using `web+spoolman:clear`, which will cause the esphome to POST to moonraker in a way that causes it to suspend tracking.

**Comment by beikeland** [comment]
I use a load cell to detect spools being unloaded and run the esphome yaml below to clear the active spool for that particular printer; I don't think a universal QR code to clear filament from Spoolman point  of view will work as you can have multiple clients, and in the case of moonraker just omitting the ID will clear the spool.

```yaml
            then:
              - http_request.post:
                  url: http://klipper.local:7125/server/spoolman/spool_id
                  request_headers:
                    Content-Type: application/json
                  body: "{}"
```
