### ISSUE TITLE
Unable to run Spoolman in Docker Container on MacOS

### ISSUE THREAD

**Issue by cruiten** [Donkie/Spoolman#441]
**Describe the bug**
If followed the Docker installation instructions for Spoolman, but when I try to start the container it continually reports the following errors:

<img width="1452" alt="Screen Shot 2024-08-10 at 2 45 48 PM" src="https://github.com/user-attachments/assets/2be7aa73-3ac8-4cd1-8ff1-1e7ec006ce2d">

I performed the "sudo chown -R 1000:1000 data" command, but that had no effect on the problem.

**To Reproduce**
Followed the instructions located here: https://github.com/Donkie/Spoolman?tab=readme-ov-file#docker-install

**Expected behavior**
Expected that Spoolman application would start.

**Screenshots**

**Spoolman Host (please complete the following information):**
 - Installation type: Docker
 - Installed version: 0.19.3
 - OS and Distro: MacOS 12.7.5
 - Database type: SQLite

**Desktop (please complete the following information):**
 - OS: MacOS 12.7.5
 - Browser Chrome
 - 
**Additional context**

**Comment by cruiten** [comment]
Updated macOS to 12.7.6, but this did not resolve the problem.

**Comment by cruiten** [comment]
Oops, it appears that I closed this issue by mistake...

**Comment by RonanRaven** [comment]
Would you mind printing the permissions using `ls -n data/` to make sure the permissions are correct? 

Another option might be to just use a docker volume, so it would turn the compose into something like:
```
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      # Mount the host machine's docker volume into the container's /home/app/.local/share/spoolman directory
      # "docker volume ls" to show the volume, and a "docker volume rm <spoolman vol from ls>" to permanently remove it
      - spoolman_data:/home/app/.local/share/spoolman
    ports:
      # Map the host machine's port 7912 to the container's port 8000
      - "7912:8000"
    environment:
      - TZ=Europe/Stockholm # Optional, defaults to UTC
volumes:
  spoolman_data:
```
keep in mind, you'll need to delete the volume if you want to permanently remove the data. docker compose down does not remove volumes.
