### ISSUE TITLE
invalid mount config for type "bind"

### ISSUE THREAD

**Issue by kacper19990** [Donkie/Spoolman#556]
**Describe the bug**
When composing the docker image, the error of 
```Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/raspberry/spoolman/data```  is returned to the user

**To Reproduce**
Copy the first install code block
```
version: '3.8'
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      # Mount the host machine's ./data directory into the container's /home/app/.local/share/spoolman directory
      - type: bind
        source: ./data # This is where the data will be stored locally. Could also be set to for example `source: /home/pi/printer_data/spoolman`.
        target: /home/app/.local/share/spoolman # Do NOT modify this line
    ports:
      # Map the host machine's port 7912 to the container's port 8000
      - "7912:8000"
    environment:
      - TZ=Europe/Stockholm # Optional, defaults to UTC
```
Try to compose docker

**Expected behavior**
Docker image should compose correctly.

The issue is fixed by doing ```mkdir data``` in the folder.

**Screenshots**

**Spoolman Host (please complete the following information):**
 - Installation type: [Docker or Standalone]
 - Installed version: [e.g. 0.17.0, can be found at the bottom of your spoolman website if you don't know]
 - OS and Distro: [e.g. Ubuntu, Raspbian]
 - Database type: [SQLite, PostgreSQL, etc]

**Desktop (please complete the following information):**
 - OS: Raspbian 64 Bit
 - Browser [e.g. Chrome, Firefox, Safari, ...]

**Additional context**
