### ISSUE TITLE
Invaid Port for uvicorn on k8s

### ISSUE THREAD

**Issue by DizzieNight** [Donkie/Spoolman#647]
**Describe the bug**
I am getting an invalid port value when starting the container. I am using kubernetes and I had it working for a few days but I am now stuck and not sure how to specify the port for uvicorn.

**To Reproduce**
1. Start container
2. See error about uvicorn port

**Expected behavior**
Should startup and use port 80

**Screenshots**

![Image](https://github.com/user-attachments/assets/585419f3-2e47-48d8-a7d9-cc9e2beccca8)

**Spoolman Host (please complete the following information):**
 - Installation type: Kubernetes Conatiner
 - Installed version: N/A
 - OS and Distro: Talos Linux
 - Database type: PostgreSQL

**Desktop (please complete the following information):**
 - OS: Bazzite Linux
 - Browser Firefox

**Additional context**
Below is my deployment yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman
  namespace: 3dprinting
  labels:
    app: spoolman
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spoolman
  template:
    metadata:
      labels:
        app: spoolman
    spec:
      containers:
      - name: spoolman
        image: ghcr.io/donkie/spoolman:latest
        startupProbe:
         httpGet:
           path: /
           port: 8000
         failureThreshold: 30
         periodSeconds: 10
        readinessProbe:
         httpGet:
           path: /
           port: 8000
         initialDelaySeconds: 5
         periodSeconds: 10
        livenessProbe:
         httpGet:
           path: /
           port: 8000
         initialDelaySeconds: 5
         periodSeconds: 10
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: spoolman
            mountPath: "/home/app/.local/share/spoolman"
        env:
          - name: SPOOLMAN_DB_HOST
            value: "spoolman-postgresql-rw"
          - name: SPOOLMAN_DB_PORT
            value: "5432"
          - name: SPOOLMAN_DB_NAME
            value: "spoolman"
          - name: SPOOLMAN_DB_USERNAME
            value: "spoolman"
          - name: SPOOLMAN_DB_PASSWORD
            value: "spoolman"
          - name: SPOOLMAN_DB_TYPE
            value: "postgres"
      # initContainers:
      #  - name: db-perms
      #    image: busybox:latest
      #    restartPolicy: Always
      #    command: ['sh', '-c', 'chown -R 1000:1000 /home/app/.local/share/spoolman']
      #    volumeMounts:
      #      - name: spoolman
      #        mountPath: /home/app/.local/share/spoolman
      volumes:
        - name: spoolman
          persistentVolumeClaim:
            claimName: spoolman
```
