### ISSUE TITLE
Allow the QR code to be configured as a URL

### ISSUE THREAD

**Issue by samwiseg0** [Donkie/Spoolman#68]
Instead of having to open spoolman and scan the QR code. The QR code can link directly to the spool. This would allow users to be able to pull out their phone and immediately link to the spool. 

This would allow for a streamlined workflow. 

In order to not break compatibility with the current implementation this could ideally be configureable.

**Comment by Donkie** [comment]
I didn't want to specify any URL in the QR code since it can change and then you'd need to re-print all your labels.

Instead the intention is that you scan the codes using the spoolman client with your phone, or a frontend can also implement scanning so that you can for example set the spool directly by showing the QR code to your printer camera. That is something that is totally possible with this setup. Fluidd should already support it.

**Comment by samwiseg0** [comment]
That makes total sense but having the option would be nice. I can see where the current method should be the default .

I personally think it's a clunky workflow when I can just pull out my phone swipe up and tap. Vs having to open an app and then find the option to take a picture of the spool. 

I get that you would have to reprint your labels if your URL changes but you already have to put spoolman in front of a reverse proxy to use the camera. It is really easy to keep the url the same if anything happens in that case. A warning when using this option to the user would suffice as well as it not being the default I think would mitigate all risk.

**Comment by Bloodpack** [comment]
> That makes total sense but having the option would be nice. I can see where the current method should be the default .
> 
> I personally think it's a clunky workflow when I can just pull out my phone swipe up and tap. Vs having to open an app and then find the option to take a picture of the spool.
> 
> I get that you would have to reprint your labels if your URL changes but you already have to put spoolman behind a reverse proxy to use the camera without browser hacks. It is really easy to keep the url the same if anything happens in that case. A warning when using this option to the user would suffice as well as it not being the default I think would mitigate all risk.

i agree 100% 

if you have to use a reverse proxy anyway to be able to use the camera then the URL should be specified in the QRCode, in zhat case you can change host computers ant the URL is always the same

**Comment by bryanshellpuppy** [comment]
I have a QR code scanner gun, and I would like the URL feature as well. If there was a search box that I could click in, then scan the QR code that would be cool, or just a straight URL to the spool. The current setup with a camera is not ideal if you have 100+ spools and you want to scan the code and remove from stored inventory. Like default state is stored and you can click in the record to move it to in an AMS or InUse or some other term. Great work btw!

**Comment by platini76** [comment]
excuse me for my stupidity, but I dont' understand the sense of qr code in actual life.... I try to read it and has no point...

**Comment by samwiseg0** [comment]
> I have a QR code scanner gun, and I would like the URL feature as well. If there was a search box that I could click in, then scan the QR code that would be cool, or just a straight URL to the spool. The current setup with a camera is not ideal if you have 100+ spools and you want to scan the code and remove from stored inventory. Like default state is stored and you can click in the record to move it to in an AMS or InUse or some other term. Great work btw!

I agree. I have over a 100 spools and currently use [snipe-it](https://snipeitapp.com/) this is the only thing holding me back from switching.

**Comment by samturner3** [comment]
+1
I thought this is how the QR code scanning did work when installing, disappointed it is not a URL 👎 
I have spoolman setup on docker on my server (not printer - has no camera anyway) so I can easily have a static local URL.

I want to just open camera on my phone, scan QR from label and have the spool page pop up...

**Comment by samturner3** [comment]
+ A QR code for a location, which would open a page with list of spools in that location where we can edit; helpful when rearranging on the fly

**Comment by samturner3** [comment]
@Donkie Opened PR for this feature https://github.com/Donkie/Spoolman/pull/461

**Comment by b2un0** [comment]
i like the feature, but can we also add a feature to change the full url and only add the `{id}` for the Spool ID as replacer?

for example, i have all my Spools also in Home Assistant as [Tag](https://www.home-assistant.io/integrations/tag/) and prefixed the id with `spoolman_`

![image](https://github.com/user-attachments/assets/f440e0ea-88a4-4859-8f4e-49fc2c481568)

so the qr code in this example contains a full URL with the tag ID like this
`https://www.home-assistant.io/tag/spoolman_1`

on scan, the Home Assistant App starts and trigger his Tag.

Then, i run an automation which trigger this [RSTful comman](https://www.home-assistant.io/integrations/rest_command) to the Moonraker Spoolman [Set Active Spool](https://moonraker.readthedocs.io/en/latest/web_api/#set-active-spool) API

```yaml
alias: Crafty - Read any Spool tag
mode: single
triggers:
  - event_type: tag_scanned
    trigger: event
conditions:
  - condition: template
    value_template: "{% set tag_id = trigger.event.data.tag_id %}{{ \"spoolman_\" in tag_id }}"
    enabled: true
actions:
  - action: rest_command.crafty_set_spool_id
    data:
      spool_id: >-
        {% set parts = trigger.event.data.tag_id.split('spoolman_')  %}  {{ parts[1] }}
  - action: script.notification_family
    data:
      title: Crafty
      message: "{{ trigger.event.data.name }}"
```

```yaml
rest_command:
  crafty_set_spool_id:
    url:  http://192.168.155.111:7125/server/spoolman/spool_id
    method: POST
    headers:
      accept: "application/json"
      user-agent: 'Mozilla/5.0 {{ useragent }}'
      x-api-key: !secret crafty_api_key
    payload: '{"spool_id": {{ spool_id }}}'
    content_type:  'application/json; charset=utf-8'
```

this works fine with NFC Tags But i would also like to add this URL into the generated qr code from spoolman like this
`https://www.home-assistant.io/tag/spoolman_{id}`

credits goes to @floyduww from this comment
https://github.com/marcolivierarsenault/moonraker-home-assistant/issues/342#issuecomment-2587185634
