### ISSUE TITLE
Host from subpath

### ISSUE THREAD

**Issue by mkuf** [Donkie/Spoolman#95]
Hi there, 

I'd like to host spoolman Api and the Frontend via a proxy under a subpath e.g. http://host/spoolman

Looking at the fastapi documentation (https://fastapi.tiangolo.com/advanced/behind-a-proxy/) this should be possible by adding the `--root-path` parameter when starting uvicorn but I had no success with that. 

This is the example setup I used for testing:
```yaml
services:
  spoolman:
    image: ghcr.io/donkie/spoolman:edge
    restart: unless-stopped
    command: 
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--root-path"
      - "/spoolman"
    volumes:
      - ./data:/home/app/.local/share/spoolman
    ports:
      - 8000:8000
    labels:
      traefik.enable: true
      traefik.http.services.spoolman.loadbalancer.server.port: 8000
      traefik.http.routers.spoolman.entrypoints: web
      traefik.http.routers.spoolman.rule: PathPrefix(`/spoolman`)
      traefik.http.routers.spoolman.middlewares: strip-spoolman@docker
      traefik.http.middlewares.strip-spoolman.stripprefix.prefixes: /spoolman

  traefik:
    image: traefik:v2.5
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

When navigating to http://localhost/spoolman, a blank white page is presented w/ the titlebar showing `Spoolman`.  
The Webapp does not seem to honor the altered root path and requests files from `/` instead of `/spoolman`.  
![image](https://github.com/Donkie/Spoolman/assets/11882946/8cc353c7-6d9a-4420-a541-660339d65d07)  

Api requests get forwarded to the frontend, which is also not the desired behaiour.   
```
~$ curl http://localhost/spoolman/api/v1
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#DC7734" />
    <meta name="description" content="Spoolman UI" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Spoolman</title>
    <script type="module" crossorigin src="/assets/index-9c13beb6.js"></script>
    <link rel="stylesheet" href="/assets/index-c7b46f6e.css">
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

  </body>
</html>
```

To rule out a misconfiguration of the proxy, I tried to access the container directly via its port.  
When accessing http://localhost:8000/spoolman, the frontend loads and shows a 404, while a request to the api behaves the same way as described above.

Any guidance on how to achive this, or does this require code changes?

-Markus
